# Generated by Django 4.1.7 on 2023-04-15 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='topic_name',
            new_name='Topic_name',
        ),
    ]
